version: "3.9"

services:
  # Frontend 1 (misal untuk Internal / Port 3000)
  frontend-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${FE1_API_URL:-http://192.168.245.191:3210/api}
        NEXT_PUBLIC_SOCKET_BASE_URL: ${FE1_WS_URL:-ws://192.168.245.191:3001}
    container_name: cmwi-frontend-1
    ports:
      - "3000:3000"
    networks:
      - cmwi-network
    restart: unless-stopped

  # Frontend 2
  frontend-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${FE2_API_URL:-http://192.168.245.156:3210/api}
        NEXT_PUBLIC_SOCKET_BASE_URL: ${FE2_WS_URL:-ws://192.168.245.156:3001}
    container_name: cmwi-frontend-2
    ports:
      - "3005:3000"
    networks:
      - cmwi-network
    restart: unless-stopped

networks:
  cmwi-network:
    name: cmwi-network
    external: true
